name: 1-Fetch Live m3u8

on:
  schedule:
    - cron: '01 0/2 * * *'
  workflow_dispatch:
  workflow_run:
    workflows:
      - "---Verify URLS--"
      - "ZZ-Clean Old m3u8s"
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Install yt-dlp
        run: |
          curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          chmod a+rx /usr/local/bin/yt-dlp
      - name: Delay for 10 seconds
        run: sleep 10

      - name: Fetch latest changes from remote
        run: |
          git fetch origin main
          # Pull changes from remote, auto-resolve conflicts with remote changes
          git pull origin main --no-edit

      - name: Rebase local changes with fetched changes
        run: git rebase origin/main

      - name: Create current_channels directory
        run: mkdir -p ./current_channels

      - name: Read channel information from alt_urls.txt
        run: |
          # Clear the contents of live_status.txt
          echo "" > live_status.txt
          while IFS=, read -r channel_name group channel_url; do
            # Modify channel_name using sed regex: remove spaces and trim to 3 words
            sanitized_channel_name=$(echo "$channel_name" | sed -E 's/[^a-zA-Z0-9]+/-/g; s/^([^-]+-[^-]+-[^-]+).*/\1/; s/-//g')

            # Create the directory only if it doesn't exist
            mkdir -p "./current_channels/$group"

            # Create the file only if it doesn't exist
            touch "./current_channels/$group/$sanitized_channel_name.m3u8"

            # Check if the channel is live
            live_status="Not Live"
            if yt-dlp --geo-bypass-country CA --print is_live "$channel_url" | grep -q "True"; then
              live_status="Live"
              echo "$channel_name is live! Updating $sanitized_channel_name.m3u8 with the current live stream!"
              {
                echo "#EXTM3U"
                echo "#EXT-X-VERSION:3"
                echo "#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000"
                yt-dlp --geo-bypass-country CA --print urls "$channel_url"
              } | sudo tee "./current_channels/$group/$sanitized_channel_name.m3u8" >/dev/null
            else
              # If not live, create the m3u8 file with the specified format
              {
                echo "#EXTM3U"
                echo "#EXT-X-VERSION:3"
                echo "#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000"
              } | sudo tee "./current_channels/$group/$sanitized_channel_name.m3u8" >/dev/null
            fi

            # Append live status information to live_status.txt using sanitized channel name
            echo "$sanitized_channel_name - $live_status - $(date)" >> live_status.txt
          done < ./program/alt_urls.txt

      - name: git add
        run: |
          git add -A
          ls -la

      - name: Commit changes
        run: |
          git diff --cached --quiet || git commit -m "Updated"

      - name: Force push changes
        run: git push --force origin main
