name: zzz-Channel Logger Workflow

on:
  workflow_run:
    workflows: ["2-Generate m3u"]
    types:
      - completed
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for 10 seconds
        run: sleep 10s

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PAT_YTLM_TOKEN }}

      - name: Open and Process File
        run: |
          while read -r line; do
            # Check if ", " exists in the line
            if [[ ! $line =~ ", " ]]; then
                echo "Error: \", \" not found in the line. Exiting script."
                exit 0
            fi

            # Remove "New: " from the line
            channel_info=$(echo "$line" | sed 's/New: //')

            # Extract channel_name by finding the first ", " and removing everything after it
            channel_name=$(echo "$channel_info" | awk -F ', ' '{print $1}')

            # Check if the channel_name exists in current_channels.txt
            if ! grep -q "$channel_name" current_channels.txt; then
                echo "$channel_name not found. Adding $channel_name to youtube_channel_info.txt"
                echo "$line" >> youtube_channel_info.txt
            else
                echo "$channel_name already exists. Disregarding."
            fi
          done < youtube_channel_info.txt

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Update Channel Logger Workflow" || true
          git push || true
