name: Channel Logger Workflow

on:
  workflow_run:
    workflows: ["Build M3U Playlist"]
    types:
      - completed
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for 10 seconds
        run: sleep 10s

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PAT_YTLM_TOKEN }}

      - name: Open and Process File
        run: |
          while read -r line; do
            # Remove "New: " from the line
            channel_info=$(echo "$line" | sed 's/New: //')
  
            # Extract channel_name by finding the first ", " and removing everything after it
            channel_name=$(echo "$channel_info" | awk -F ', ' '{print $1}')
  
            # Search for channel_name in ytm.yml
            if grep -q "$channel_name" .github/workflows/ytm.yml; then
              echo "$channel_name has been added, transferred to log"
  
              # Copy line to recently_added_channels.txt
              echo "$line" >> recently_added_channels.txt
  
              # Remove line from youtube_channel_info.txt
              awk -v pattern="$line" '$0 != pattern' youtube_channel_info.txt > tmpfile && mv tmpfile youtube_channel_info.txt
            else
              echo "Searched for $channel_name, match not found."
  
              # Restore the original line to youtube_channel_info.txt
              echo "$line" >> youtube_channel_info.txt
            fi
          done < youtube_channel_info.txt

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Update Channel Logger Workflow" || true
          git push || true
