name: Delete M3U8 Files

on:
  push:
    branches:
      - main

jobs:
  delete_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete .m3u8 files
      run: |
        find . -type f -name "*.m3u8" -delete

    - name: Commit and Push Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Delete .m3u8 files"
        git push
