name: Delete M3U8 Files

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    inputs:
      manual_run:
        description: 'Run the workflow manually'
        default: 'false'

jobs:
  delete_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete .m3u8 files
      run: |
        files=$(find . -type f -name "*.m3u8")
        if [ -z "$files" ]; then
          echo "Directories are already clean - Nothing to delete"
        else
          find . -type f -name "*.m3u8" -delete
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Delete .m3u8 files"
          git push
        fi
