name: Delete M3U8 Files

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      manual_run:
        description: 'Run the workflow manually'
        default: 'false'

jobs:
  delete_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete .m3u8 files
      run: |
        files=$(find . -type f -name "*.m3u8")
        if [ -z "$files" ]; then
          echo "Directories are already clean - Nothing to delete"
        else
          find . -type f -name "*.m3u8" -delete
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Delete .m3u8 files"
          git push
        fi

# Add a new job to trigger the "Get YouTube Live m3u8" workflow
  trigger_get_youtube_live_m3u8:
    needs: delete_files
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Run trigger script
      run: |
        const { Octokit } = require('@octokit/rest');
        const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
        
        const response = await octokit.actions.createWorkflowDispatch({
          owner: 'YTM',
          repo: 'YTM',
          workflow_id: '7616522628', // Replace with your actual workflow ID
          ref: 'main', // Replace with the branch where the workflow is located
          inputs: {
            // Add any necessary inputs for the workflow
          }
        });
        console.log('Workflow triggered:', response.data);
