name: 2-Generate VOD m3u

on:
  workflow_dispatch:
    workflows: ["ZZ-Combine VOD Step 2"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: GoonerM466/YTM
        ref: main

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Rebase changes
      run: git pull --rebase origin main

    - name: Run Channel Generation Script
      run: |
        echo "Current directory: $GITHUB_WORKSPACE"
        echo "List of files:"
        find ./vod -maxdepth 2 -type f -name '*.m3u8' -print0 | while IFS= read -r -d '' file; do
          echo "Processing file: $file"
          category=$(basename "$(dirname "$file")")
          channel=$(basename "$(dirname "$(dirname "$file")")")
          video_url="https://raw.githubusercontent.com/GoonerM466/YTM/main/$file"

          # Check if the channel already exists in combined_VOD_playlist.m3u8
          if grep -q "#EXTINF:-1 tvg-id=\"$channel\" tvg-name=\"$channel\"" combined_VOD_playlist.m3u8; then
            # Remove existing entries with the same $channel_name and the following line
            sed -i "/#EXTINF:-1 tvg-id=\"$channel\" tvg-name=\"$channel\"/,+1d" combined_VOD_playlist.m3u8
          fi

          # Add new entry
          echo "#EXTINF:-1 tvg-id=\"$channel\" tvg-name=\"$channel\" tvg-logo=\"\" group-title=\"$category\",$channel"
          echo "$video_url"
        done > combined_VOD_playlist.m3u8

    - name: Check for Changes and Pull & Push
      run: |
        git diff --exit-code && echo "No changes detected" || (git add combined_VOD_playlist.m3u8 && git commit -m "Update Combined VOD Playlist" && git pull --no-edit origin main && git push)
        # Check if there are any conflicts after pull
        git diff --check
        if [ $? -ne 0 ]; then
          # Auto-resolve conflicts by choosing one side
          git checkout --ours combined_VOD_playlist.m3u8
          git add combined_VOD_playlist.m3u8
          git commit -m "Auto-resolve conflicts"
          git push origin main
        fi
