name: Generate VOD m3u

on:
  push:
    branches:
      - main

jobs:
  generate-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "Your Name"
          git config user.email "your.email@example.com"

      - name: Rebase changes
        run: git pull origin main --rebase

      - name: Wipe contents of combined_VOD_playlist.m3u8
        run: echo "#extm3u" > combined_VOD_playlist.m3u8

      - name: Find and list m3u8 files excluding "videos" folder
        run: |
          find ./vod -type f -name "*.m3u8" -not -path "./vod/*/videos/*" -exec ls -l {} \; > ./program/temp/VOD-m3u-temp.txt

      - name: Commit changes
        run: |
          git add combined_VOD_playlist.m3u8 ./program/temp/VOD-m3u-temp.txt
          git commit -m "Update VOD m3u files"
          
      - name: Push changes
        run: git push origin main
