name: D-Fetch VOD

on:
  push:
    branches:
      - main

jobs:
  extract-m3u8:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        search_term:
          - beinsportshaber
          - other_search_term

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp

    - name: Fetch latest changes from remote
      run: |
        git fetch origin main
        git pull origin main --no-edit
        git rebase origin/main

    - name: Read search term from file
      id: read-search-term
      run: |
        content=$(cat ./program/alt_urls.txt)
        search_term=$(echo "$content" | cut -d ',' -f 1 | awk -F', ' '{print $1}')
        echo "::set-output name=search_term::$search_term"

    - name: Print extracted search term
      run: |
        echo "Extracted Search Term: ${{ steps.read-search-term.outputs.search_term }}"
        echo "SEARCH_TERM=${{ steps.read-search-term.outputs.search_term }}" >> $GITHUB_ENV

    - name: Extract top 3 video URLs
      id: extract-urls
      run: |
        search_term=${{ steps.read-search-term.outputs.search_term }}
        # Create directory if it doesn't exist
        mkdir -p ./vod/$search_term
        # Touch the file to ensure it exists
        touch ./vod/$search_term/vod_videos.m3u8
        start_time=$(date +%s)
        while [ $(( $(date +%s) - $start_time )) -lt 30 ]; do
          timeout 5 yt-dlp "ytsearch:${search_term}" --get-url --skip-download
          if [ $? -eq 0 ]; then
            echo "Video URL found for ${search_term}"
            break
          fi
        done

    - name: Create M3U8 file
      run: |
        echo "#EXTM3U" > ./vod/${{ steps.read-search-term.outputs.search_term }}/vod_videos.m3u8
        echo "#EXT-X-VERSION:3" >> ./vod/${{ steps.read-search-term.outputs.search_term }}/vod_videos.m3u8
        video_number=1
        while read -r line; do
          echo "#EXT-X-STREAM-INF:NAME=\"FHD\",RESOLUTION=1920x1080,BANDWIDTH=${video_number}" >> ./vod/${{ steps.read-search-term.outputs.search_term }}/vod_videos.m3u8
          echo "${line}" >> ./vod/${{ steps.read-search-term.outputs.search_term }}/vod_videos.m3u8
          ((video_number++))
        done < ./vod/${{ steps.read-search-term.outputs.search_term }}/vod_videos.m3u8

    - name: Commit changes
      run: |
        git add -A
        git diff --cached --quiet || git commit -m "Updated M3U8 files"
        git push origin main
