name: D-Fetch VOD

on:
  push:
    branches:
      - main

jobs:
  extract-m3u8:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp

    - name: Fetch latest changes from remote
      run: |
        git fetch origin main
        git pull origin main --no-edit
        git rebase origin/main

    - name: Read search terms from file
      run: |
        IFS=',' read -ra search_terms <<< $(cat ./program/alt_urls.txt)
        for term in "${search_terms[@]}"; do
          echo "Processing search term: $term"
          
          mkdir -p ./vod/$term
          touch ./vod/$term/vod_videos.m3u8

          start_time=$(date +%s)
          for i in {1..3}; do
            echo "Attempting to extract video URL (Attempt $i)..."
            m3u8_url=$(timeout 5 yt-dlp "ytsearch:${term}" --get-url --skip-download)
            if [ $? -eq 0 ]; then
              echo "Video URL found: $m3u8_url"
              echo $m3u8_url >> ./vod/$term/vod_videos.m3u8
            else
              echo "Error extracting video URL. Skipping to the next."
              break
            fi
          done

          echo "M3U8 content:"
          cat ./vod/$term/vod_videos.m3u8

          echo "Creating M3U8 file..."
          echo "#EXTM3U" > ./vod/$term/vod_videos_temp.m3u8
          echo "#EXT-X-VERSION:3" >> ./vod/$term/vod_videos_temp.m3u8
          video_number=1
          while read -r line; do
            echo "#EXT-X-STREAM-INF:NAME=\"FHD\",RESOLUTION=1920x1080,BANDWIDTH=${video_number}" >> ./vod/$term/vod_videos_temp.m3u8
            echo "${line}" >> ./vod/$term/vod_videos_temp.m3u8
            ((video_number++))
          done < ./vod/$term/vod_videos.m3u8

          mv ./vod/$term/vod_videos_temp.m3u8 ./vod/$term/vod_videos.m3u8

          echo "Committing changes..."
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add -A
          git diff --cached --quiet || git commit -m "Updated M3U8 files"
          git push origin main
        done
