name: Fetch VOD VideoID

on:
  workflow_dispatch:

jobs:
  extract-m3u8:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp

    - name: Fetch latest changes from remote
      run: |
        git fetch origin main
        git pull origin main --no-edit

    - name: Run Fetch VOD VideoID script
      working-directory: ./scripts
      run: |
        python fetch_vod_video_id.py

    - name: Commit and push changes
      run: |
        cd ./scripts
        echo "Committing changes..."
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add -A
        git diff --cached --quiet || git commit -m "Updated VOD VideoID files"
        git push origin main
