name: Fetch VOD VideoID

on:
  workflow_dispatch:

jobs:
  extract-m3u8:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp

    - name: Fetch latest changes from remote
      run: |
        git fetch origin main
        git pull origin main --no-edit

    - name: Extract channel information
      run: |
        echo "Extracting channel information..."
        while IFS=, read -r channel_name group channel_url; do
          echo "Processing $channel_name from $group group with URL $channel_url/streams"
         video_ids=$(yt-dlp "$channel_url/streams" --get-id --datebefore "$(date -u +"%Y%m%d%H%M%S")" --max-downloads 3 --skip-download)

          if [ -n "$video_ids" ]; then
            echo "Video IDs for $channel_name: $video_ids"
            touch VOD_to_fetch.txt
            echo "$video_ids, $group, $channel_url" >> VOD_to_fetch.txt
            echo "Added entry to VOD_to_fetch.txt"
          else
            echo "No videos found for $channel_name"
          fi
        done < current_channels.txt

    - name: Display VOD_to_fetch.txt content
      run: cat VOD_to_fetch.txt

    - name: Commit changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add VOD_to_fetch.txt
        git commit -m "Update VOD_to_fetch.txt"
        git push
