name: D-Fetch VOD

on:
  push:
    branches:
      - main

jobs:
  extract-video-ids:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp

    - name: Fetch latest changes from remote
      run: |
        git fetch origin main
        git pull origin main --no-edit
        git rebase origin/main

    - name: Read live URLs from file and extract video IDs
      run: |
        while IFS=, read -r channel_name group live_url; do
          echo "Processing live URL: $live_url"
          
          # Modify the live_url as needed
          modified_url="${live_url/live/streams}"
          
          echo "Modified URL: $modified_url"

          video_id=$(yt-dlp "$modified_url" --get-id --skip-download 2>/dev/null)

          if [ $? -eq 0 ]; then
            echo "Video ID found: $video_id"
            echo "$channel_name, $group, https://www.youtube.com/watch?v=$video_id" >> "./program/vod_to_fetch.txt"
          else
            echo "Error extracting video ID from $live_url."
          fi
        done < ./program/alt_urls.txt

    - name: Commit changes and push to main
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add -A
        git diff --cached --quiet || git commit -m "Updated video IDs"
        git push origin main
