name: Extract and Fetch VOD

on:
  push:
    branches:
      - main

jobs:
  extract_and_fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Git Config
      run: |
        git config user.email "you@example.com"
        git config user.name "Your Name"
    
    - name: Prepare VOD File
      run: |
        touch VOD_to_fetch.txt
        > VOD_to_fetch.txt
        touch processed_video_ids.txt
        > processed_video_ids.txt
    
    - name: Create Temp File with Modified Channel Names
      run: |
        awk -F ', ' '{ gsub(/ /, "_", $1); print $0 }' current_channels.txt > temp_channels.txt
    
    - name: Extract and Fetch VOD
      run: |
        # Your existing extraction and fetching steps

    - name: Replace Underscores with Spaces in Output File
      run: |
        sed -i 's/_/ /g' VOD_to_fetch.txt
    
    - name: Add, Commit, and Push Changes
      run: |
        git add VOD_to_fetch.txt
        git add processed_video_ids.txt
        git commit -m "Update VOD_to_fetch.txt with latest videos"
        git pull origin main
        git merge -s ours origin/main
        git push origin main

    - name: Trigger Python Script
      run: |
        chmod +x ./scripts/filter_VOD.py
        ./scripts/filter_VOD.py
