name: Extract and Fetch VOD

on:
  workflow_dispatch:

jobs:
  extract_and_fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Git Config
      run: |
        git config user.email "you@example.com"
        git config user.name "Your Name"

    - name: Prepare VOD File
      run: |
        touch VOD_to_fetch.txt
        touch processed_video_ids.txt
        touch current_channels.txt
        touch temp_channels.txt

    - name: Check and Create Files
      run: |
        if [ ! -f VOD_to_fetch.txt ]; then touch VOD_to_fetch.txt; fi
        if [ ! -f processed_video_ids.txt ]; then touch processed_video_ids.txt; fi
        if [ ! -f current_channels.txt ]; then touch current_channels.txt; fi
        if [ ! -f temp_channels.txt ]; then touch temp_channels.txt; fi

    - name: Create Temp File with Modified Channel Names
      run: |
        awk -F ', ' '{ gsub(/ /, "_", $1); print $0 }' current_channels.txt > temp_channels.txt

    - name: Extract and Fetch VOD
      run: |
        # ... (your existing script)

    - name: Replace Underscores with Spaces in Output File
      run: |
        sed -i 's/_/ /g' VOD_to_fetch.txt

    - name: Add, Commit, and Push Changes
      run: |
        git add VOD_to_fetch.txt
        git add processed_video_ids.txt
        git commit -m "Update VOD_to_fetch.txt with latest videos"
        git pull origin main
        git merge -s ours origin/main
        git push origin main
