name: D-Fetch VOD

on:
  push:
    branches:
      - main

jobs:
  extract-m3u8:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp

    - name: Fetch latest changes from remote
      run: |
        git fetch origin main
        git pull origin main --no-edit
        git rebase origin/main

    - name: Read live URLs from file
      run: |
        while IFS=, read -r channel_name group live_url; do
          echo "Processing live URL: $live_url"
          
          # Modify the live_url as needed
          modified_url="${live_url/live/streams}"
          
          echo "Modified URL: $modified_url"

          mkdir -p ./vod/$channel_name
          m3u8_file="./vod/$channel_name/vod_videos.m3u8"

          # Truncate the file before writing
          : > "$m3u8_file"

          start_time=$(date +%s)
          for i in {1..2}; do
            echo "Attempting to extract video URL (Attempt $i)..."
            m3u8_url=$(timeout 30 yt-dlp "$modified_url" --get-url --skip-download 2>&1)
            if [ $? -eq 0 ] && [ -n "$m3u8_url" ]; then
              echo "Video URL found: $m3u8_url"
              echo $m3u8_url >> "$m3u8_file"
              break  # Break out of the loop if a URL is found
            else
              echo "Error extracting video URL. Retrying..."
              # For the second attempt, retry with the modified URL without "/live" or "/streams"
              modified_url="${live_url/live/}"
            fi
          done

          if [ ! -s "$m3u8_file" ]; then
            echo "No video URL found. Moving on to the next channel."
            continue
          fi

          echo "M3U8 content:"
          cat "$m3u8_file"

          echo "Creating M3U8 file..."
          echo "#EXTM3U" > "./vod/$channel_name/vod_videos_temp.m3u8"
          echo "#EXT-X-VERSION:3" >> "./vod/$channel_name/vod_videos_temp.m3u8"
          video_number=1
          while read -r line; do
            echo "#EXT-X-STREAM-INF:NAME=\"FHD\",RESOLUTION=1920x1080,BANDWIDTH=${video_number}" >> "./vod/$channel_name/vod_videos_temp.m3u8"
            echo "${line}" >> "./vod/$channel_name/vod_videos_temp.m3u8"
            ((video_number++))
          done < "$m3u8_file"

          mv "./vod/$channel_name/vod_videos_temp.m3u8" "$m3u8_file"

          echo "Committing changes..."
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add -A
          git diff --cached --quiet || git commit -m "Updated M3U8 files"
          git push origin main
        done < ./program/alt_url.txt
