name: Get YouTube Live m3u8

on:
  schedule:
    - cron: '45 0/2 * * *'
  workflow_dispatch:
  workflow_run:
    workflows:
      - "New Channel Scrape Workflow"
      - "Delete M3U8 Files"
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp
    - name: Delay for 10 seconds
      run: sleep 10

    - name: Pull latest changes
      run: git pull origin main

    - name: Rebase changes
      run: git pull --rebase origin main

    - name: Create current_channels directory
      run: mkdir -p ./current_channels
      
    - name: Run Fetch_m3u8 Script
      run: pythion ./scripts/fetch_m3u8.py

    - name: Print workspace
      run: ls -la
      
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git diff --cached --quiet || git commit -m Updated
        git push origin main
