name: Find Live Channels

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:

jobs:
  update-channels:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib yt-dlp

    - name: Run the script
      run: python find_live.py

    - name: Run the script
      run: python find_music.py

    - name: Check for changes
      id: check-changes
      run: |
        git diff --exit-code || echo "Changes detected"

    - name: Commit and push changes
      if: steps.check-changes.outputs.result != 'Changes detected'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add all_live_channels.txt
        git commit -m "Update live channels [skip ci]"
        git push
