name: Generate XMLTV

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Get YouTube Live m3u8"
    types:
      - completed

jobs:
  generate_xmltv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Delay before script execution
      run: sleep 30

    - name: Execute script and generate XMLTV
      run: python generate_xmltv.py > combined_epg.xml

    - name: Check if changes exist
      id: check_changes
      run: |
        git diff --exit-code || echo "Changes detected"

    - name: Commit changes
      if: steps.check_changes.outputs.return-code == '0'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add combined_epg.xml
        git commit -m "Generate XMLTV"
        git push
