name: meta test

on:
  schedule:
    - cron: '15 2/12 * * *'
  workflow_dispatch:

jobs:
  extract_and_fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Git Config
      run: |
        git config user.email "you@example.com"
        git config user.name "Your Name"

    - name: Create Temp Directory
      run: mkdir -p ./program/temp

    - name: Prepare VOD File
      run: touch ./program/temp/VOD_to_fetch_temp.txt

    - name: Fetch video information
      run: |
        set -x
        while IFS=, read -r channel_name group video_url video_image; do
          # Check if any of the required variables is empty
          if [ -z "$channel_name" ] || [ -z "$group" ] || [ -z "$video_url" ] || [ -z "$video_image" ]; then
            echo "One or more required variables is empty. Skipping..."
            continue
          fi

          # Construct modified video URL
          channel_url=$(echo "$channel_name" | tr -d ' ' | tr '_' '')
          modified_video_url="$video_url&ab_channel=$channel_url"
          
          # Extract video information (dummy values for now)
          title="Dummy Title"
          upload_date="2022-01-30"
          view_count="1000"

          # Print values for debugging
          echo "Channel: $channel_name, Group: $group, Video URL: $video_url, Image: $video_image, Title: $title, Upload Date: $upload_date, View Count: $view_count"

          # Save information back to the source file (commented out for now)
          # echo "$channel_name, $group, $video_url, $video_image, $title, $upload_date, $view_count" >> ./program/temp/VOD_to_fetch.txt
        done < ./program/temp/VOD_to_fetch_temp.txt
        set +x

    - name: Add, Commit, and Push Changes
      run: |
        git add ./program/temp/VOD_to_fetch_temp.txt
        git commit -m "Update VOD_to_fetch_temp.txt with latest videos & metadata"
        git pull origin main --no-rebase
        git merge -s ours origin/main
        git push origin main
