name: meta test

on:
  schedule:
    - cron: '15 2/12 * * *'
  workflow_dispatch:

jobs:
  extract_and_fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Git Config
      run: |
        git config user.email "you@example.com"
        git config user.name "Your Name"

    - name: Create Temp Directory
      run: mkdir -p ./program/temp

    - name: Prepare VOD File
      run: |
        touch ./program/temp/VOD_to_fetch_temp.txt
        > ./program/temp/VOD_to_fetch_temp.txt

    - name: Fetch video information
      run: |
        while IFS=, read -r channel_name group video_url video_image; do
          # Check if any of the required variables is empty
          if [ -z "$channel_name" ] || [ -z "$group" ] || [ -z "$video_url" ] || [ -z "$video_image" ]; then
            echo "One or more required variables is empty. Skipping..."
            continue
          fi

          # Construct modified video URL
          channel_url=$(echo "$channel_name" | tr -d ' ' | tr '_' '')
          modified_video_url="$video_url&ab_channel=$channel_url"

          # Extract video information
          video_page_content=$(curl -s "$modified_video_url") || { echo "Failed to fetch video page for $modified_video_url"; exit 1; }
          title=$(echo "$video_page_content" | grep -oP '<title>\K(.*)(?=<\/title>)' || echo "Title not found")
          upload_date=$(echo "$video_page_content" | grep -oP '<meta itemprop="uploadDate" content="\K[^"]+' || echo "Upload date not found")
          view_count=$(echo "$video_page_content" | grep -oP '{"viewCount":{"simpleText":"\K[^"]+' || echo "View count not found")

          # Save information back to the source file
          echo "$channel_name, $group, $video_url, $video_image, $title, $upload_date, $view_count" >> ./program/temp/VOD_to_fetch.txt
        done < ./program/temp/VOD_to_fetch_temp.txt

    - name: Add, Commit, and Push Changes
      run: |
        git add ./program/temp/VOD_to_fetch.txt
        git add ./program/temp/processed_video_ids.txt
        git commit -m "Update VOD_to_fetch.txt with latest videos & metadata"
        git pull origin main --no-rebase
        git merge -s ours origin/main
        git push origin main
