name: Fetch Video Information

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours

jobs:
  fetch_video_info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch video information
      run: |
        set -x
        while IFS=, read -r channel_name group video_url video_image; do
          # Check if any of the required variables is empty
          if [ -z "$channel_name" ] || [ -z "$group" ] || [ -z "$video_url" ] || [ -z "$video_image" ]; then
            echo "One or more required variables is empty. Skipping..."
            continue
          fi

          # Construct modified video URL (commented out for now)
          # ...

          # Extract video information (dummy values for now)
          title="Dummy Title"
          upload_date="2022-01-30"
          view_count="1000"

          # Print values for debugging
          echo "Channel: $channel_name, Group: $group, Video URL: $video_url, Image: $video_image, Title: $title, Upload Date: $upload_date, View Count: $view_count"

          # Save information back to the source file
          echo "$channel_name, $group, $video_url, $video_image, $title, $upload_date, $view_count" >> ./program/temp/VOD_to_fetch_temp.txt
        done < ./program/temp/VOD_to_fetch_temp.txt
        set +x

    - name: Add, Commit, and Push Changes
      run: |
        git add ./program/temp/VOD_to_fetch_temp.txt
        git commit -m "Update VOD_to_fetch_temp.txt with latest videos & metadata"
        git pull origin main --no-rebase
        git merge -s ours origin/main
        git push origin main
