name: Metadata Workflow

on:
workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pyyaml google-api-python-client

    - name: Run scrape script
      run: |
        echo "Running metadata.py"
        python metadata.py > output.txt 2>&1 || echo "Script failed with exit code $?"
        echo "Script Output:"
        cat output.txt
        echo "Metadata Dump:"
        cat meta_dump.txt
      continue-on-error: true

    - name: Remove untracked files
      run: git clean -fdX

    - name: Print XML Contents
      run: cat combined_epg.xml

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add combined_epg.xml
        git commit -m "Update combined epg.xml"
        git push
