name: Move Python Files

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  move_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Move Python Files
      run: |
        mkdir -p ./scripts/
        find . -type f -name "*.py" -exec mv {} ./scripts/ \;

    - name: Commit and Push Changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Move Python files to ./scripts/"
        git push
