name: New Channel Scrape Workflow

on:
  push:
    paths:
      - youtube_channel_info.txt
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PAT_YTLM_TOKEN }}

      - name: Search and Remove Git Steps
        run: |
          # Search for and remove the "git add," "commit & push" steps from ytm.yml
          sed -i '/- name: git add/,/- git push/d' .github/workflows/ytm.yml

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Adjust the Python version as needed

      - name: Process YouTube Channel Info
        run: |
          python ./.scripts/process_youtube_channel_info.py
          # Replace 'process_youtube_channel_info.py' with the actual script name

      - name: Add Git Steps
        run: |
          # Add git add, commit, and push steps to ytm.yml
          echo "
              - name: git add
                run: |
                  git add -A
                  ls -la
              - name: commit & push
                run: |
                  git diff --cached --quiet || git commit -m "Updated"
                  git push origin main
          " >> .github/workflows/ytm.yml
          
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Update YTM workflow"
          git push
