name: New Channel Scrape Workflow

on:
  push:
    paths:
      - youtube_channel_info.txt
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: GoonerM466/YTM
        ref: main

    - name: Read Channel Info
      run: |
        while IFS= read -r line; do
          # Extracting values from the line
          channel_name=$(echo "$line" | cut -d '|' -f 1 | tr -d ' ')
          group_name=$(echo "$line" | cut -d '|' -f 2 | tr -d ' ')
          channel_url=$(grep -E '^http' <<< "$line" | sed -n 1p | tr -d ' ')
  
          if [[ $channel_url == "https://www.youtube.com/"* ]]; then
            # Appending new entry to ytm.yml
            echo "- name: $channel_name
              run: |
                touch ./$group_name/$channel_name.m3u8
                sudo cat > ./$group_name/$channel_name.m3u8 <<EOL
                #EXTM3U
                #EXT-X-VERSION:3
                #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
                \$(yt-dlp --print urls $channel_url)
                EOL" >> .github/workflows/ytm.yml
          fi
        done < youtube_channel_info.txt

    - name: Check for Changes and Push
      run: |
        git diff --exit-code && echo "No changes detected" || (git add .github/workflows/ytm.yml && git commit -m "Update YTM workflow" && git push)
