name: New Channel Scrape Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout
      with:
        repository: GoonerM466/YTM
        ref: main

    - name: Run Channel Generation Script
      run: ./generate_ytm.sh

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Check for Changes
      run: |
        git diff --exit-code || git commit -am "Update channels based on youtube_channel_info.txt" && git push
