name: New Channel Scrape Workflow

on:
  push:
    paths:
      - youtube_channel_info.txt
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PAT_YTLM_TOKEN }}

      - name: Backup YTM Workflow File
        run: cp .github/workflows/ytm.yml .github/workflows/ytm_backup.yml

      - name: Wait for 30 Seconds
        run: sleep 30

      - name: Read Channel Info
        run: |
          cat youtube_channel_info.txt | while IFS=', ' read -r _ channel_name group_name channel_url; do
            if [[ $channel_url == "https://www.youtube.com/"* ]]; then
              # Use awk to insert new entries on line 23 with proper indentation
              awk -v channel_name="$channel_name" -v group_name="$group_name" -v channel_url="$channel_url" '
                NR==23{
                  print "    - name: " channel_name
                  print "      run: |"
                  print "        touch ./" group_name "/" channel_name ".m3u8"
                  print "        sudo cat > ./" group_name "/" channel_name ".m3u8 <<EOL"
                  print "        #EXTM3U"
                  print "        #EXT-X-VERSION:3"
                  print "        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000"
                  print "        $(yt-dlp --print urls " channel_url ")"
                  print "        EOL"
                  print "           "
                  next
                }
                { print }
              ' .github/workflows/ytm.yml > temp.yml && mv temp.yml .github/workflows/ytm.yml
            fi
          done

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add and Check for Changes
        run: |
          # Add files and check for changes
          git add .github/workflows/ytm.yml .github/workflows/ytm_backup.yml
          git diff --exit-code .github/workflows/ytm_backup.yml .github/workflows/ytm.yml || git commit -m "Update YTM workflow"

      - name: Push Changes
        run: |
          # Push changes only if there are any
          if [ -n "$(git status --porcelain)" ]; then
            echo "Pushing changes..."
            git push
          else
            echo "No changes to push."
          fi

          # Remove the temporary backup file
          rm .github/workflows/ytm_backup.yml
