name: New Channel Scrape Workflow

on:
  push:
    paths:
      - youtube_channel_info.txt
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PAT_YTLM_TOKEN }}

      - name: Backup YTM Workflow File
        run: cp .github/workflows/ytm.yml .github/workflows/ytm_backup.yml

      - name: Read Channel Info
        run: |
          while IFS= read -r line; do
            # Extracting values from the line
            channel_name=$(echo "$line" | awk -F ', ' '{print $1}' | sed 's/^New: //')
            group_name=$(echo "$line" | awk -F ', ' '{print $2}' | tr -d ' ')
            channel_url=$(echo "$line" | awk -F ', ' '{print $3}' | tr -d ' ')
  
            if [[ $channel_url == "https://www.youtube.com/"* ]]; then
              # Change "New: " tag to "Added!!"
              line=$(echo "$line" | sed 's/New:/Added!!/')
              
              # Escape special characters in the URL
              escaped_url=$(printf '%s\n' "$channel_url" | sed -e 's/[]\/$*.^[]/\\&/g')

              # AWK code to insert new entries at the end of the file
              awk -v channel_name="$channel_name" -v group_name="$group_name" -v escaped_url="$escaped_url" '
                /- name: git add/{flag=1; next} /git commit -m "Update YTM workflow"/{flag=0} !flag {print}
                END {
                  printf "    - name: %s\n", channel_name
                  printf "      run: |\n"
                  printf "        mkdir -p ./%s\n", group_name
                  printf "        touch ./%s/%s.m3u8\n", group_name, channel_name
                  printf "        sudo cat > ./%s/%s.m3u8 <<EOL\n", group_name, channel_name
                  printf "        #EXTM3U\n"
                  printf "        #EXT-X-VERSION:3\n"
                  printf "        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000\n"
                  printf "        $(yt-dlp --print urls \"%s\")\n", escaped_url
                  printf "        EOL\n"
                  printf "    - name: git add\n"
                  printf "      run: |\n"
                  printf "        git add -A\n"
                  printf "        ls -la\n"
                  printf "    - name: commit & push\n"
                  printf "      run: |\n"
                  printf "        git commit -m \"links are updated\"\n"
                  printf "        git push\n"
                }
              ' .github/workflows/ytm.yml > temp.yml && mv temp.yml .github/workflows/ytm.yml
              
              # Print the modified line to indicate it has been processed
              echo "$line"
            fi
          done < youtube_channel_info.txt

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Update YTM workflow"
          git push
