name: New Channel Scrape Workflow

on:
  push:
    paths:
      - youtube_channel_info.txt
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PAT_YTLM_TOKEN }}

      - name: Backup YTM Workflow File
        run: cp .github/workflows/ytm.yml .github/workflows/ytm_backup.yml

      - name: Read Channel Info
        run: |
          while IFS= read -r line; do
            channel_name=$(echo "$line" | awk -F ', ' '{print $1}' | sed 's/^New: //')
            group_name=$(echo "$line" | awk -F ', ' '{print $2}' | tr -d ' ')
            channel_url=$(echo "$line" | awk -F ', ' '{print $3}' | tr -d ' ')
  
            if [[ $channel_url == "https://www.youtube.com/"* ]]; then
              line=$(echo "$line" | sed 's/New:/Added!!/')
              
              awk -v channel_name="$channel_name" -v group_name="$group_name" -v channel_url="$channel_url" '
                /- name: git add/{flag=1; next} /git commit -m "Update YTM workflow"/{flag=0} !flag {print}
                END {
                  print "    - name: " channel_name
                  print "      run: |"
                  print "        mkdir -p ./" group_name
                  print "        touch ./" group_name "/" channel_name ".m3u8"
                  print "        sudo cat > ./" group_name "/" channel_name ".m3u8 <<EOL"
                  print "        #EXTM3U"
                  print "        #EXT-X-VERSION:3"
                  print "        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000"
                  printf "        $(yt-dlp 
