name: New Channel Scrape Workflow

on:
  push:
    paths:
      - youtube_channel_info.txt
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PAT_YTLM_TOKEN }}

      - name: Backup YTM Workflow File
        run: cp .github/workflows/ytm.yml .github/workflows/ytm_backup.yml

      - name: Wait for 30 Seconds
        run: sleep 30

      - name: Read Channel Info
        run: |
          while IFS= read -r line; do
            # Extracting values from the line
            channel_name=$(echo "$line" | awk -F ', ' '{print $1}' | tr -d ' ')
            group_name=$(echo "$line" | awk -F ', ' '{print $2}' | tr -d ' ')
            channel_url=$(echo "$line" | awk -F ', ' '{print $3}' | tr -d ' ')
  
            if [[ $channel_url == "https://www.youtube.com/"* ]]; then
              # Change "New: " tag to "Added!!"
              line=$(echo "$line" | sed 's/New:/Added!!/')
              
              # Remove "New: " tag from channel name
              channel_name=$(echo "$channel_name" | sed 's/^New: //')
              
              # AWK code to insert new entries at the end of the file
              awk -v channel_name="$channel_name" -v group_name="$group_name" -v channel_url="$channel_url" '
                /- name: git add/{flag=1; next} /git commit -m "Update YTM workflow"/{flag=0} !flag {print}
                END {
                  print "    - name: " channel_name
                  print "      run: |"
                  print "        mkdir -p ./" group_name
                  print "        touch ./" group_name "/" channel_name ".m3u8"
                  print "        sudo cat > ./" group_name "/" channel_name ".m3u8 <<EOL"
                  print "        #EXTM3U"
                  print "        #EXT-X-VERSION:3"
                  print "        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000"
                  print "        \$(yt-dlp --print urls " channel_url ")"
                  print "        EOL"
                  print "           "
                  print ""
                  print "    - name: git add"
                  print "      run: |"
                  print "        git add -A"
                  print "        ls -la"
                  print ""
                  print "    - name: commit & push"
                  print "      run: |"
                  print "        git commit -m \"links are updated\""
                  print "        git push"
                }
              ' .github/workflows/ytm.yml > temp.yml && mv temp.yml .github/workflows/ytm.yml
              
              # Print the modified line to indicate it has been processed
              echo "$line"
            fi
          done < youtube_channel_info.txt

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Modify YTM Workflow File
        run: |
          # Look for the line containing "- name: git add" and replace until the end of the file
          awk '/- name: git add/{flag=1; next} /git commit -m "Update YTM workflow"/{flag=0} !flag' .github/workflows/ytm.yml > temp.yml && mv temp.yml .github/workflows/ytm.yml

          # Add the following code after all new entries
          echo "    - name: git add"
          echo "      run: |"
          echo "        git add -A"
          echo "        ls -la"
          echo ""
          echo "    - name: commit & push"
          echo "      run: |"
          echo "        git commit -m \"links are updated\""
          echo "        git push"
