name: Extract M3U8 Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp

    - name: Extract VideoID and Get M3U8
      run: |
        # Extract VideoID from test.txt
        VIDEO_ID=$(grep -oP 'https://www.youtube.com/watch\?v=\K[^&]+' test.txt)

        # Clear existing content of test.m3u8
        echo "" > test.m3u8

        # Use yt-dlp to print M3U8 URL and write to test.m3u8
        yt-dlp --print urls "https://www.youtube.com/watch?v=$VIDEO_ID" > test.m3u8

    - name: Commit and Push Changes
      run: |
        git add test.m3u8
        git commit -m "Update M3U8 file"
        git push
