name: Extract and Format M3U8 URL Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp

    - name: Extract VideoID and Get M3U8 URLs
      run: |
        # Extract VideoID from test.txt
        VIDEO_ID=$(grep -oP 'https://www.youtube.com/watch\?v=\K[^&]+' test.txt)

        # Use yt-dlp to get combined M3U8 URL for formats 312+251
        M3U8_URL=$(yt-dlp --format 312+234 --get-url --no-playlist "https://www.youtube.com/watch?v=$VIDEO_ID")

        # Filter URLs that end with ".m3u8" and write to test.m3u8 using echo
        echo "#EXTINF:-1 tvg-id=\"TEST\" tvg-name=\"TEST\" tvg-logo=\"\" group-title=\" TEST\",TEST" > test.m3u8
        echo "$M3U8_URL" | grep -E '\.m3u8$' >> test.m3u8

    - name: Commit and Push Changes
      run: |
        git add test.m3u8
        git commit -m "Update M3U8 file"
        git push
