name: Debug M3U8 Formats Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp

    - name: Get Debug Information about M3U8 Formats
      run: |
        # Extract VideoID from test.txt
        VIDEO_ID=$(grep -oP 'https://www.youtube.com/watch\?v=\K[^&]+' test.txt)

        # Use yt-dlp to list all available formats and write to test_debug file
        yt-dlp --list-formats "https://www.youtube.com/watch?v=$VIDEO_ID" > test_debug

    - name: Commit and Push Debug Information
      run: |
        git add test_debug
        git commit -m "Add M3U8 format debug information"
        git push
