name: Extract M3U8 Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp

    - name: Extract URL from test.txt
      run: |
        URL=$(cat test.txt)
        URL=$(echo "$URL" | sed 's/&/\\&/g')  # Sanitize URL with ampersand
        echo "Extracted URL: $URL"

    - name: Download M3U8 using yt-dlp
      run: |
        yt-dlp -o video.m3u8 "$URL"

    - name: Write M3U8 link to test.m3u
      run: |
        echo "$URL" > test.m3u
