name: Extract M3U8 Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp

    - name: Extract video ID from test.txt
      run: |
        URL=$(cat test.txt)
        VIDEO_ID=$(echo $URL | awk -F 'v=' '{print $2}' | awk -F '&' '{print $1}')
        echo "Extracted Video ID: $VIDEO_ID"

    - name: Download M3U8 using yt-dlp
      run: |
        VIDEO_URL="https://www.youtube.com/watch?v=$VIDEO_ID"
        yt-dlp -o "video_$VIDEO_ID.m3u8" "$VIDEO_URL"

    - name: Write M3U8 link to test.m3u8
      run: |
        echo "$VIDEO_URL" > test.m3u8
