name: Get YouTube Live m3u8

on:
  schedule:
    - cron: '45 0/2 * * *'
  workflow_dispatch:
  workflow_run:
    workflows:
      - "New Channel Scrape Workflow"
      - "Delete M3U8 Files"
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp
    - name: Delay for 10 seconds
      run: sleep 10

    - name: Pull latest changes
      run: git pull origin main

    - name: Rebase changes
      run: git pull --rebase origin main

    - name: Create current_channels directory
      run: mkdir -p ./current_channels

    - name: Read channel information from current_channels.txt
      run: |
        while IFS=, read -r channel_name group channel_url; do
          # Modify channel_name using sed regex: remove spaces and trim to 3 words
          channel_name=$(echo "$channel_name" | sed -E 's/[^a-zA-Z0-9]+/-/g; s/^([^-]+-[^-]+-[^-]+).*/\1/; s/-//g')
          mkdir -p "./current_channels/$group"
          
          # Check if the m3u8 file exists at the channel address
          if yt-dlp --print info "$channel_url" | grep -q "m3u8"; then
            echo "Found m3u8 for $channel_name at $channel_url. Downloading..."
            yt-dlp --print urls "$channel_url" > "./current_channels/$group/$channel_name.m3u8"
          elif yt-dlp --print info "$channel_url" | grep -q "404 Not Found"; then
            echo "404: $channel_name - $channel_url" >> 404.txt
            echo "No m3u8 found for $channel_name at $channel_url. Added to 404.txt."
          else
            echo "Unknown error for $channel_name at $channel_url."
          fi
        done < current_channels.txt

    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git diff --cached --quiet || git commit -m Updated
        git push origin main
