name: Get YouTube Live m3u8

on:
  schedule:
    - cron: '0 0/1 * * *'
  workflow_dispatch:
  workflow_run:
    workflows: ["New Channel Scrape Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp
    - name: Delay for 10 seconds
      run: sleep 10

    - name: Pull latest changes
      run: git pull origin main

    - name: Process channels and update ytm.yml
      run: |
        while IFS=, read -r channel_name channel_group channel_url; do
          # Check if there are any live streams on the /streams endpoint
          video_info_json=$(yt-dlp --print-json "${channel_url}/streams")
          live_streams=$(echo "${video_info_json}" | jq -r '.entries | length')

          if [ "${live_streams}" -gt 0 ]; then
            echo "Processing live channel: ${channel_name}, ${channel_group}, ${channel_url}"

            # Add entry to ytm.yml
            new_entry="    - name: Get ${channel_name}\n"\
                      "      run: |\n"\
                      "        touch ./${channel_group}/${channel_name}.m3u8\n"\
                      "        sudo cat > ./${channel_group}/${channel_name}.m3u8 <<EOL\n"\
                      "        #EXTM3U\n"\
                      "        #EXT-X-VERSION:3\n"\
                      "        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000\n"\
                      "        $(yt-dlp --force-generic-extractor --get-url ${channel_url}/streams)\n"\
                      "        EOL\n"

            # Append new entry to ytm.yml
            echo -e "${new_entry}" >> .github/workflows/ytm.yml
          else
            echo "No live streams found for ${channel_name}. Skipping..."
          fi
        done < youtube_channel_info.txt

    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git diff --cached --quiet || git commit -m "links are updated"
        git push origin main
