name: Get YouTube Live m3u8

on:
  schedule:
    - cron: '0 0/1 * * *'
  workflow_dispatch:
  workflow_run:
    workflows: ["New Channel Scrape Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Install yt-dlp
        run: |
          curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          chmod a+rx /usr/local/bin/yt-dlp
      - name: Delay for 10 seconds
        run: sleep 10

      - name: Check and update live channels
        run: |
          all_channels=(
            "beinsportshaber,spor,https://www.youtube.com/@beinsportsturkiye"
            "AFCAsianCup,spor,https://www.youtube.com/@AFCAsianCup"
            "talkSPORT,spor,https://www.youtube.com/@talkSPORT"
            "EERIEISSSS,ytl,https://www.youtube.com/@EERIEISSSS"
            "Jimmy_Broadbent,ytl,https://www.youtube.com/@Jimmy_Broadbent"
            "deadeyedelboy,ytl,https://www.youtube.com/@deadeyedelboy"
            "NBCNews,news,https://www.youtube.com/@NBCNews"
            "SkyNews,news,https://www.youtube.com/@SkyNews"
            "ABCNews,news,https://www.youtube.com/@ABCNews"
            "HitsRadio,music,https://www.youtube.com/watch?v=HQtFR3mhzOY"
            "classicmusic-top1,music,https://www.youtube.com/@classicmusic-top1/live"
            "FobosPlanet,music,https://www.youtube.com/@FobosPlanet/live"
            "DPWorldTour,spor,https://www.youtube.com/@DPWorldTour/live"
            "GBNewsOnline,news,https://www.youtube.com/@GBNewsOnline/live"
          )

          for channel_info in "${all_channels[@]}"; do
            ./update_channels.sh "$channel_info"
          done

      - name: git add
        run: |
          git add -A
      - name: commit & push
        run: |
          git diff --cached --quiet || git commit -m "links are updated"
          git push origin main
