jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Install latest yt-dlp
        run: |
          curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          chmod a+rx /usr/local/bin/yt-dlp
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq
      - name: Pull latest changes
        run: git pull origin main
      - name: Rebase changes
        run: git pull --rebase origin main
      - name: Set execute permissions for check_channels.sh
        run: chmod +x check_channels.sh
      - name: Run check_channels.sh
        run: bash check_channels.sh
      - name: git add
        run: |
          git add -A
          ls -la
      - name: commit & push
        run: |
          git diff --cached --quiet || git commit -m "links are updated"
          git push origin main
