name: Get YouTube Live m3u8

on:
  schedule:
    - cron: '0 0/1 * * *'
  workflow_dispatch:
  workflow_run:
    workflows: ["New Channel Scrape Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp
    - name: Delay for 10 seconds
      run: sleep 10

    - name: Pull latest changes
      run: git pull origin main

    - name: Rebase changes
      run: git pull --rebase origin main

    - name: Get beINSportsHaber
      run: |
        touch ./spor/beinsportshaber.m3u8
        start_time=$(date +%s)
        while true; do
          if yt-dlp --print urls https://www.youtube.com/@beinsportsturkiye/streams || yt-dlp --print --get-id https://www.youtube.com/@beinsportsturkiye --dateafter now-5hours; then
            break
          fi
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge 60 ]; then
            echo "Time limit reached. Moving on to the next channel."
            break
          fi
          sleep 10  # Adjust sleep duration as needed
        done

    - name: Get AFCAsianCup
      run: |
        touch ./spor/AFCAsianCup.m3u8
        start_time=$(date +%s)
        while true; do
          if yt-dlp --print urls https://www.youtube.com/@AFCAsianCup/streams || yt-dlp --print --get-id https://www.youtube.com/@AFCAsianCup --dateafter now-5hours; then
            break
          fi
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge 60 ]; then
            echo "Time limit reached. Moving on to the next channel."
            break
          fi
          sleep 10  # Adjust sleep duration as needed
        done

    - name: Get talkSPORT
      run: |
        touch ./spor/talkSPORT.m3u8
        start_time=$(date +%s)
        while true; do
          if yt-dlp --print urls https://www.youtube.com/@talkSPORT/streams || yt-dlp --print --get-id https://www.youtube.com/@talkSPORT --dateafter now-5hours; then
            break
          fi
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge 60 ]; then
            echo "Time limit reached. Moving on to the next channel."
            break
          fi
          sleep 10  # Adjust sleep duration as needed
        done

    - name: Get EERIEISSSS
      run: |
        touch ./ytl/EERIEISSSS.m3u8
        start_time=$(date +%s)
        while true; do
          if yt-dlp --print urls https://www.youtube.com/@EERIEISSSS/streams || yt-dlp --print --get-id https://www.youtube.com/@EERIEISSSS --dateafter now-5hours; then
            break
          fi
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge 60 ]; then
            echo "Time limit reached. Moving on to the next channel."
            break
          fi
          sleep 10  # Adjust sleep duration as needed
        done

    - name: Get JimmyBroadbent
      run: |
        touch ./ytl/JimmyBroadbent.m3u8
        start_time=$(date +%s)
        while true; do
          if yt-dlp --print urls https://www.youtube.com/@Jimmy_Broadbent/streams || yt-dlp --print --get-id https://www.youtube.com/@Jimmy_Broadbent --dateafter now-5hours; then
            break
          fi
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge 60 ]; then
            echo "Time limit reached. Moving on to the next channel."
            break
          fi
          sleep 10  # Adjust sleep duration as needed
        done

    - name: Get DeadEyeDelBoy
      run: |
        touch ./ytl/DeadEyeDelBoy.m3u8
        start_time=$(date +%s)
        while true; do
          if yt-dlp --print urls https://www.youtube.com/@deadeyedelboy/streams || yt-dlp --print --get-id https://www.youtube.com/@deadeyedelboy --dateafter now-5hours; then
            break
          fi
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge 60 ]; then
            echo "Time limit reached. Moving on to the next channel."
            break
          fi
          sleep 10  # Adjust sleep duration as needed
        done

    - name: Get NBCNews
      run: |
        touch ./news/NBCNews.m3u8
        start_time=$(date +%s)
        while true; do
          if yt-dlp --print urls https://www.youtube.com/@NBCNews/streams || yt-dlp --print --get-id https://www.youtube.com/@NBCNews --dateafter now-5hours; then
            break
          fi
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge 60 ]; then
            echo "Time limit reached. Moving on to the next channel."
            break
          fi
          sleep 10  # Adjust sleep duration as needed
        done

    - name: Get SkyNews
      run: |
        touch ./news/SkyNews.m3u8
        start_time=$(date +%s)
        while true; do
          if yt-dlp --print urls https://www.youtube.com/@SkyNews/streams || yt-dlp --print --get-id https://www.youtube.com/@SkyNews --dateafter now-5hours; then
            break
          fi
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge 60 ]; then
            echo "Time limit reached. Moving on to the next channel."
            break
          fi
          sleep 10  # Adjust sleep duration as needed
        done

    - name: Get ABCNews
      run: |
        touch ./news/ABCNews.m3u8
        start_time=$(date +%s)
        while true; do
          if yt-dlp --print urls https://www.youtube.com/@ABCNews/streams || yt-dlp --print --get-id https://www.youtube.com/@ABCNews --dateafter now-5hours; then
            break
          fi
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge 60 ]; then
            echo "Time limit reached. Moving on to the next channel."
            break
          fi
          sleep 10  # Adjust sleep duration as needed
        done

    - name: Get HitsRadio
      run: |
        touch ./music/HitsRadio.m3u8
        start_time=$(date +%s)
        while true; do
          if yt-dlp --print urls https://www.youtube.com/watch?v=HQtFR3mhzOY || yt-dlp --print --get-id https://www.youtube.com/watch?v=HQtFR3mhzOY --dateafter now-5hours; then
            break
          fi
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge 60 ]; then
            echo "Time limit reached. Moving on to the next channel."
            break
          fi
          sleep 10  # Adjust sleep duration as needed
        done

    - name: Get Classic80s
      run: |
        touch ./music/Classic80s.m3u8
        start_time=$(date +%s)
        while true; do
          if yt-dlp --print urls https://www.youtube.com/@classicmusic-top1/streams || yt-dlp --print --get-id https://www.youtube.com/@classicmusic-top1 --dateafter now-5hours; then
            break
          fi
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge 60 ]; then
            echo "Time limit reached. Moving on to the next channel."
            break
          fi
          sleep 10  # Adjust sleep duration as needed
        done

    - name: Get FobosPlanet
      run: |
        touch ./music/FobosPlanet.m3u8
        start_time=$(date +%s)
        while true; do
          if yt-dlp --print urls https://www.youtube.com/@FobosPlanet/streams || yt-dlp --print --get-id https://www.youtube.com/@FobosPlanet --dateafter now-5hours; then
            break
          fi
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge 60 ]; then
            echo "Time limit reached. Moving on to the next channel."
            break
          fi
          sleep 10  # Adjust sleep duration as needed
        done

    - name: DPWorldTour
      run: |
        mkdir -p ./spor
        touch ./spor/DPWorldTour.m3u8
        start_time=$(date +%s)
        while true; do
          if yt-dlp --print urls "https://www.youtube.com/@DPWorldTour/streams" || yt-dlp --print --get-id https://www.youtube.com/@DPWorldTour --dateafter now-5hours; then
            break
          fi
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge 60 ]; then
            echo "Time limit reached. Moving on to the next channel."
            break
          fi
          sleep 10  # Adjust sleep duration as needed
        done

    - name: Get GBNews
      run: |
        touch ./news/GBNews.m3u8
        start_time=$(date +%s)
        while true; do
          if yt-dlp --print urls https://www.youtube.com/@GBNewsOnline/streams || yt-dlp --print --get-id https://www.youtube.com/@GBNewsOnline --dateafter now-5hours; then
            break
          fi
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ $elapsed_time -ge 60 ]; then
            echo "Time limit reached. Moving on to the next channel."
            break
          fi
          sleep 10  # Adjust sleep duration as needed
        done

    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git diff --cached --quiet || git commit -m "links are updated"
        git push origin main
