name: Get YouTube Live m3u8

on:
  schedule:
    - cron: '45 0/2 * * *'
  workflow_dispatch:
  workflow_run:
    workflows:
      - "New Channel Scrape Workflow"
      - "Delete M3U8 Files"
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp
    - name: Delay for 10 seconds
      run: sleep 10

    - name: Pull latest changes
      run: git pull origin main

    - name: Rebase changes
      run: git pull --rebase origin main

    - name: Create current_channels directory
      run: mkdir -p ./current_channels

    - name: Read channel information from current_channels.txt
      run: |
        while IFS=, read -r channel_name group channel_url; do
          echo "Processing $channel_name at $channel_url..."

          # Modify channel_name using sed regex: remove spaces and trim to 3 words
          channel_name=$(echo "$channel_name" | sed -E 's/[^a-zA-Z0-9]+/-/g; s/^([^-]+-[^-]+-[^-]+).*/\1/; s/-//g')
          mkdir -p "./current_channels/$group"

          # Construct live_url based on different YouTube channel URL formats
          if [[ "$channel_url" == *"youtube.com/@*"* ]]; then
            # Extract the username from the channel URL
            username=$(echo "$channel_url" | sed 's|.*youtube.com/@\(.*\)/live|\1|')
            live_url="https://www.youtube.com/$username/live"
          else
            live_url="$channel_url"
          fi

          # Check if the m3u8 file exists at the channel address
          if yt-dlp --print info "$live_url" | grep -q "m3u8"; then
            echo "$channel_name is Live at $live_url. Downloading m3u8 link..."
            yt-dlp --print urls "$live_url" > "./current_channels/$group/$channel_name.m3u8"
          elif yt-dlp --print info "$live_url" | grep -q "404 Not Found"; then
            echo "$channel_name is 404 at $live_url. Added to 404.txt..."
            echo "404: $channel_name - $live_url" >> 404.txt
          else
            echo "$channel_name is not currently live at $live_url."
          fi

          # Append live status information to live_status.txt
          echo "$channel_name - $(date)" >> live_status.txt
        done < current_channels.txt

    - name: Print workspace
      run: ls -la
      
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git diff --cached --quiet || git commit -m Updated
        git push origin main
