name: Get YouTube Live m3u8

on:
  schedule:
    - cron: '0 0/1 * * *'
  workflow_dispatch:
  workflow_run:
    workflows:
      - "New Channel Scrape Workflow"
      - "Delete M3U8 Files"
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp
    - name: Delay for 10 seconds
      run: sleep 10

    - name: Pull latest changes
      run: git pull origin main

    - name: Rebase changes
      run: git pull --rebase origin main

    - name: Create current_channels directory
      run: mkdir -p ./current_channels

    - name: Read channel information from current_channels.txt
      run: |
        while IFS=, read -r channel_name group channel_url; do
          mkdir -p "./current_channels/$group"
          touch "./current_channels/$group/$channel_name.m3u8"
          {
            echo "#EXTM3U"
            echo "#EXT-X-VERSION:3"
            echo "#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000"
            yt-dlp --print urls "$channel_url"
          } | sudo tee "./current_channels/$group/$channel_name.m3u8" >/dev/null
          
          # Check if the channel is live
          if yt-dlp --print is_live "$channel_url" | grep -q "True"; then
            echo "$channel_name is live! Updating $channel_name.m3u8 with current live stream!"
          fi
        done < current_channels.txt

    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git diff --cached --quiet || git commit -m "links are updated"
        git push origin main
