name: zz-EC VOD URLs

on:
  workflow_dispatch:
    inputs:
      input_file:
        description: './program/temp/vod_to_fetch.txt'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Install yt-dlp
      run: |
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp

    - name: Process VOD URLs
      run: |
        set +e  # Disable exit-on-error temporarily
        while IFS=, read -r channel_name group video_url image_url; do
          # ... (your existing code)
        done < "./program/temp/vod_to_fetch.txt"
        set -e  # Enable exit-on-error again

    - name: Clean Up Folder Names
      run: |
        for group_folder in ./vod/*/; do
          # Remove leading spaces
          group_name=$(echo "$group_folder" | sed 's/^\s*//')

          # Replace other spaces with underscores
          group_name=$(echo "$group_name" | tr ' ' '_')

          # Rename the folder
          mv "$group_folder" "$group_name"
        done

    - name: Commit and Push Changes
      run: |
        git add ./vod
        git commit -m "Update vod files"
        git push
