name: ZZ-Combine VOD Step 2

on:
  workflow_run:
    workflows: ["1-Fetch Live m3u8"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: GoonerM466/YTM
        ref: main

    - name: Create temp directory
      run: mkdir -p ./program/temp

    - name: List and Save Files
      run: ls ./vod > ./program/temp/VOD_temp.txt
      working-directory: .

    - name: Process M3U8 Files
      run: |
        while IFS= read -r line; do
          if [ -d "./videos/$line" ]; then
            video_count=1
            m3u8_file="./vod/$line.m3u8"
            echo "#EXTM3U" > "$m3u8_file"
            echo "#EXT-X-VERSION:3" >> "$m3u8_file"

            for m3u8_path in $(find "./videos/$line" -name "*.m3u8"); do
              echo "#EXT-X-STREAM-INF:NAME=\"FHD\",RESOLUTION=1920x1080,BANDWIDTH=$video_count" >> "$m3u8_file"
              echo "https://raw.githubusercontent.com/GoonerM466/YTM/main/vod/$line/$(basename "$m3u8_path")" >> "$m3u8_file"
              ((video_count++))
            done
          fi
        done < ./program/temp/VOD_temp.txt

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Check for Changes and Pull & Push
      run: |
        git diff --exit-code && echo "No changes detected" || (git add ./vod/*/ && git commit -m "Update Channel M3U8 Playlists" && git pull --no-edit origin main && git push)
        # Check if there are any conflicts after pull
        git diff --check
        if [ $? -ne 0 ]; then
          # Auto-resolve conflicts by choosing one side
          git checkout --ours ./vod/*/*.m3u8
          git add ./vod/*/*.m3u8
          git commit -m "Auto-resolve conflicts"
          git push origin main
        fi
