name: ZZ-Combine VOD Step 2

on:
  workflow_run:
    workflows: ["1-Fetch Live m3u8"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: GoonerM466/YTM
        ref: main

    - name: Rebase changes
      run: git pull --rebase origin main

    - name: Run Channel Generation Script
      run: |
        find ./vod -type f -name '*.m3u8' | grep -E '/videos/.*\.m3u8$' | while IFS= read -r file; do
          channel_url="https://raw.githubusercontent.com/GoonerM466/YTM/main/${file#./}/$video_id.m3u8"
          output_directory="./vod/$(dirname "$file" | sed 's|./vod/||')"
          output_filename="$(basename "$(dirname "$file")")_vod.m3u8"
          output_file="$output_directory/$output_filename"
          
          # Clear contents of the existing m3u8 file
          echo "" > "$output_file"

          # Write header to the m3u8 file
          echo "#EXTM3U" >> "$output_file"
          echo "#EXT-X-VERSION:3" >> "$output_file"

          # Calculate video number starting from 1
          video_number=$(find "$(dirname "$file")" -type f -name '*.m3u8' | grep -E '\.m3u8$' | wc -l)
          ((video_number++))

          # Write entry to the m3u8 file
          echo "#EXT-X-STREAM-INF:NAME=\"$(basename "$(dirname "$file")")\",RESOLUTION=1920x1080,BANDWIDTH=$video_number" >> "$output_file"
          echo "$channel_url" >> "$output_file"
        done

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Check for Changes and Pull & Push
      run: |
        git diff --exit-code && echo "No changes detected" || (git add ./vod/*/ && git commit -m "Update Channel M3U8 Playlists" && git pull --no-edit origin main && git push)
        # Check if there are any conflicts after pull
        git diff --check
        if [ $? -ne 0 ]; then
          # Auto-resolve conflicts by choosing one side
          git checkout --ours ./vod/*/*.m3u8
          git add ./vod/*/*.m3u8
          git commit -m "Auto-resolve conflicts"
          git push origin main
        fi
