name: ZZ-Combine VOD Step 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: GoonerM466/YTM
        ref: main


    - name: Rebase changes
      run: git pull --rebase origin main

    - name: Run Channel Generation Script
      run: |
        find ./vod -type f -name '*.m3u8' -print0 | while IFS= read -r -d '' file; do
          group=$(dirname "$file")
          channel_name=$(basename "$(dirname "$file")")
          video_id=$(basename "$file" .m3u8)
          channel_url="https://raw.githubusercontent.com/GoonerM466/YTM/main/$file"

          if [ -n "$channel_url" ]; then
            # Clear contents of the existing m3u8 file
            echo "" > "./vod/$group/$channel_name/${channel_name}_vod.m3u8"

            # Create a separate m3u8 file for each subfolder
            mkdir -p "./vod/$group/$channel_name/videos"
            
            # Write header to the m3u8 file
            echo "#EXTM3U" >> "./vod/$group/$channel_name/${channel_name}_vod.m3u8"
            echo "#EXT-X-VERSION:3" >> "./vod/$group/$channel_name/${channel_name}_vod.m3u8"

            # Calculate video number
            video_number=$(find "./vod/$group/$channel_name/videos" -type f -name '*.m3u8' | wc -l)
            
            # Write entry to the m3u8 file
            echo "#EXT-X-STREAM-INF:NAME=\"$channel_name\",RESOLUTION=1920x1080,BANDWIDTH=$video_number" >> "./vod/$group/$channel_name/${channel_name}_vod.m3u8"
            echo "$channel_url" >> "./vod/$group/$channel_name/${channel_name}_vod.m3u8"
          fi
        done

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Check for Changes and Pull & Push
      run: |
        git diff --exit-code && echo "No changes detected" || (git add ./vod/*/ && git commit -m "Update Channel M3U8 Playlists" && git pull --no-edit origin main && git push)
        # Check if there are any conflicts after pull
        git diff --check
        if [ $? -ne 0 ]; then
          # Auto-resolve conflicts by choosing one side
          git checkout --ours ./vod/*/*.m3u8
          git add ./vod/*/*.m3u8
          git commit -m "Auto-resolve conflicts"
          git push origin main
        fi
