name: ZZ-Clean Old EPG

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # Run every day at 8am
jobs:
  clean_old_epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: List files in directory
      run: ls -R

    - name: Print input file contents
      run: cat combined_epg.xml

    - name: Run clean_old_epg.py
      run: python ./scripts/clean_old_epg.py

    - name: Print output file contents
      run: cat old_epg.xml

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --cached --quiet || git commit -m "Clean old EPG - $(date)"
        git push origin main
