name: ZZ-Combine VOD Step 2

on:
  workflow_dispatch:

jobs:
  process_vod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install tree

    - name: Create or truncate VOD_temp.txt
      run: |
        echo -n > program/temp/VOD_temp.txt

    - name: Find and list m3u8 files
      run: |
        find vod -type f -path "vod/*/videos/*.m3u8" | sed 's#^vod/##' > program/temp/VOD_temp.txt

       
    - name: Commit and push changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add .
        git commit -m "Update m3u8 files and create playlists"
        git push
