name: zz-Filter VOD

on:
  workflow_dispatch:

jobs:
  fetch-live-vod:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install yt-dlp
      run: |
        # Download the latest version of yt-dlp
        curl -L $(curl -s https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest | grep "browser_download_url.*yt-dlp" | cut -d '"' -f 4) -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp

    - name: Read channel information from VOD_to_fetch.txt
      run: |
        # Create a temporary file to store updated entries
        tmpfile=$(mktemp)

        while IFS=, read -r channel_name group video_url image_url; do
          # Check if the video is live
          if yt-dlp --print is_live "$video_url" | grep -q "True"; then
            echo "$video_url is live - discarding!"
          else
            echo "$video_url is not live - saving!"
            # If not live, append the entry to the temporary file
            echo "$channel_name,$group,$video_url,$image_url" >> "$tmpfile"
          fi
          # Introduce a 2-second delay
          sleep 2
        done < VOD_to_fetch.txt

        # Overwrite the original file with the updated entries
        mv "$tmpfile" VOD_to_fetch.txt

    - name: Commit and push changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --cached --quiet || git commit -m "Update VOD list"
        git push origin main
