name: zz-Filter VOD

on:
  workflow_dispatch:

jobs:
  filter-live-vod:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install yt-dlp and jq
      run: |
        # Install yt-dlp
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp

        # Install jq
        sudo apt-get update
        sudo apt-get install jq -y

    - name: Read channel information from VOD_to_fetch.txt
      run: |
        # Create a temporary file to store updated entries
        tmpfile=$(mktemp)

        while IFS=, read -r channel_name group video_url image_url; do
          # Replace spaces with underscores in the video URL
          video_url=$(echo "$video_url" | sed 's/ /_/g')

          # Check if the video is live using yt-dlp JSON output without downloading
          video_info=$(yt-dlp --print-json --skip-download "$video_url")
          live_status=$(echo "$video_info" | jq -r .is_live)
          
          if [ "$live_status" == "true" ]; then
            echo "$video_url is live - discarding!"
          else
            echo "$video_url is not live - saving!"
            # If not live, append the entry to the temporary file
            echo "$channel_name,$group,$video_url,$image_url" >> "$tmpfile"
          fi
          # Introduce a 2-second delay
          sleep 2
        done < VOD_to_fetch.txt

        # Overwrite the original file with the updated entries
        mv "$tmpfile" VOD_to_fetch.txt

    - name: Commit and push changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --cached --quiet || git commit -m "Filter VOD list"
        git push origin main
