name: zz-Filter VOD

on:
  workflow_dispatch:

jobs:
  filter-live-vod:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install yt-dlp and jq
      run: |
        # Install yt-dlp
        curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        chmod a+rx /usr/local/bin/yt-dlp

        # Install jq
        sudo apt-get update
        sudo apt-get install jq -y

    - name: Replace spaces in video URLs
      run: |
        awk 'BEGIN{OFS=FS=","} {match($3, /v=([^&]+)/, arr); gsub(/ /, "_", arr[1]); $3 = "https://www.youtube.com/watch?v=" arr[1]} 1' /program/temp/VOD_to_fetch.txt > /program/temp/VOD_to_fetch_temp.txt
        mv /program/temp/VOD_to_fetch_temp.txt /program/temp/VOD_to_fetch.txt

    - name: Read channel information from VOD_to_fetch.txt
      run: |
        tmpfile=$(mktemp)

        while IFS=, read -r channel_name group video_url image_url; do
          # Check if the video is live using yt-dlp JSON output without downloading
          video_info=$(yt-dlp --print-json --skip-download "$video_url")
          live_status=$(echo "$video_info" | jq -r '.is_live or (.start_time and (.start_time | fromdateiso8601 < now | not))')

          if [ "$live_status" == "true" ]; then
            echo "$video_url is live or scheduled - discarding!"
          else
            echo "$video_url is not live - saving!"
            # If not live, append the entry to the temporary file
            echo "$channel_name,$group,$video_url,$image_url" >> "$tmpfile"
          fi
          # Introduce a 2-second delay
          sleep 2
        done < /program/temp/VOD_to_fetch.txt

        # Overwrite the original file with the updated entries
        mv "$tmpfile" /program/temp/VOD_to_fetch.txt

    - name: Commit and push changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --cached --quiet || git commit -m "Filter VOD list"
        git push origin main
