name: ZZ-Test Skip

on:
  workflow_dispatch:

jobs:
  generate-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "Your Name"
          git config user.email "your.email@example.com"

      - name: Rebase changes
        run: git pull origin main --rebase

      - name: Wipe contents of combined_VOD_playlist.m3u8
        run: echo "#extm3u" > combined_VOD_playlist.m3u8

      - name: Find and list m3u8 files excluding "videos" folder
        run: |
          find ./vod -mindepth 4 -maxdepth 4 -type f -name "*.m3u8" -exec ls -l {} \; > ./program/temp/live_vod_temp.txt

      - name: Process VOD entries
        run: |
          while IFS= read -r line; do
            # Extract information from each line
            file_path=$(echo "$line" | grep -oP 'vod.*\.m3u8')
            group=$(echo "$file_path" | cut -d'/' -f2)
            channel_name=$(echo "$file_path" | cut -d'/' -f3)
            file_name=$(basename "$file_path" | cut -d'.' -f1)

            # Replace underscores with spaces only for combined_VOD_playlist.m3u8 output
            formatted_channel_name=$(echo "$channel_name" | tr '_' ' ')

            # Get additional metadata from live_vod_meta.txt
            metadata_line=$(grep "$file_name" ./program/temp/live_vod_meta.txt)
            IFS=',' read -r channel_name group video_url video_image title upload_date view_count <<< "$metadata_line"

            # Construct the channel VOD URL
            echo "#EXTINF:-1 tvg-id=\"$title - $upload_date - $view_count\" tvg-name=\"$title - $upload_date - $view_count\" tvg-logo=\"$video_image\" group-title=\"$formatted_channel_name\",$title - $upload_date - $view_count" >> test_skip.m3u8
            echo "$video_url" >> test_skip.m3u8
          done < ./program/temp/live_vod_temp.txt

      - name: Commit changes
        run: |
          git add test_skip.m3u8
          git add ./program/temp/live_vod_temp.txt
          git commit -m "Update VOD m3u files"

      - name: Push changes
        run: git push origin main
